config/routes.rb
KhojRegistration::Application.routes.draw do
  match '/info', :to => 'home#info', :as => :info
  devise_for :admins

  devise_for :users, :controllers => {:confirmations => 'confirmations'}

  resources :users, :only => [] do
    resources :indices, :only => [:index] 
  end

  root :to => 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/index.rb
class Index < ActiveRecord::Base
  validate :name, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :api_key, :document_limit, :index_count, :subscription_type, :public_url, :private_url

  has_many :indices

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(scope)
    if scope.is_a?(User)
      '#'
    elsif scope.is_a?(Admin)
      '#'
    else
      super
    end
  end

  def unauthorized_user
    flash[:notice] = I18n.t('access.restrict')
    redirect_to '/' and return
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  def show
    user = User.find_by_confirmation_token(params[:confirmation_token])
    user.public_api_key =  SecureRandom.hex(5)
    user.private_api_key = SecureRandom.hex(8)
    user.public_url = 'http://'+ user.public_api_key + '.khoj.com'
    user.private_url ='http://'+ user.private_api_key + '@' + user.public_api_key + '.khoj.com'
    user.save!
    super
  end

end

app/controllers/home_controller.rb
class HomeController <  ActionController::Base

  layout 'application'

  def index

  end
end

app/controllers/indices_controller.rb
class IndicesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_user

  def index
    @indices = @user.indices
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def load_user
    @user = User.find_by_id(params[:user_id]) 
    unauthorized_user unless @user == current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
- if user_signed_in?
  .page-header
    %h1
      Personal Info
      %small 
  .row
    .span10
      %fieldset{:style => 'margin:0px; padding:0px;'}
        %label 
          %h5 Email:
        %div
          %h5{:style => 'margin-left:150px;margin-top:5px;'}=current_user.email  
      %fieldset{:style => 'margin:0px; padding:0px;'}
        %label 
          %h5 Public URL:
        %div
          %h5{:style => 'margin-left:150px;margin-top:5px;'}=current_user.public_url 
- else
  %h1
    Welcome to Khoj.

app/views/home/info.html.haml
%ul
  %li  SignUp with Khoj and get the private key for your account.
  %li  Create an index and populate it with searchable text
  %li  Send search queries to the index and understand the results
  %li  Tweak the search results and influence the order in which they appear
  %li  Delete documents

%h2 About The Example App
%p The Tutorial shows the process for setting up an index and performing some example queries 

%h2 Step 1: Sign Up on Khoj
%h3 Private key
%h5 This is the base url for authenticated API calls. 
.well
  %h5 Example: private_key = 'test-api-key'
  %h5 Example: index_name  = 'test'
%h2 Step 2: Install khoj
.well
  %h5= "$ gem install 'khoj'"
%h2 INSTANTIATE THE CLIENT
%h3 Run the Ruby interpreter
.well
  %h5= ":001 >"
%h3 Import the Khoj client library to the Ruby interpreter by typing the following command at the prompt
.well
  %h5= ":001:0> require 'rubygems'"
  %h5= ":001:0> require 'khoj'"
%h3 Instantiate the client
.well
  %h5  Khoj.config do |c| 
  %h5  c.api_key = private_key 
  %h5  c.api_host = Khoj::Configuration::DEFAULTS[:api_host] 
  %h5  end
%h3 Get a handle to your test index
.well
  %h5 client = Khoj.client(index_name)
%h2 Step 3: Operations
%h3 Add some documents to the index.
.well
  /%h5 document = {:test => 'from the the test case', :title => 'One', :tags => ['foo', 'baz']}
  %h5 document = {:text => 'test'}
  %h5 client.add('_type:_id', value)
  %h5 Example: client.add('test:1', document)
%h3 Search
%h4 Get index by providing _type and _id
.well
  %h5 client.get('_type:_id')
  %h5 Example: client.get('test:1')
  %h5 Response:  {"_index"=>"test-api-key-test", "_type"=>"test", "_id"=>"1", "_version"=>1, "exists"=>true, "_source"=>{"text"=>"test"}}
%h4 By default it will check in text field
.well
  %h5 client.search(query_term)
  %h5 Example: client.search('test')
  %h5 Response:    {"took"=>91, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>1, "max_score"=>1.6931472, "hits"=>[{"_index"=>"test-api-key-test", "_type"=>"test", "_id"=>"1", "_score"=>1.6931472, "_source"=>{"text"=>"test"}}]}}
%h3 Specify field in which query  is to be searched
.well
  %h5 document = {:text => 'test', :title => 'One'}
  %h5 client.add('test:1', document)
  %h5 client.search(query_term, :field => field_name)
  %h5 Example: client.search('one', :field => 'title')
  %h5 Response: {"_index"=>"test-api-key-test", "_type"=>"test", "_id"=>"1", "_version"=>2, "exists"=>true, "_source"=>{"text"=>"test", "title"=>"One"}}

%h3 Category Filters(Facet)
.well
  %h5 document_1 = {:text => 'test', :title => 'One', :laptop => ['dell', 'apple']}
  %h5 document_2 = {:text => 'test', :title => 'two', :laptop => ['acer', 'apple']}
  %h5 Example: client.add('test:1', document_1)
  %h5 Example: client.add('test:2', document_2)
  %h5 client.search(query_term, {:field => field_name, :type => _type, :category_filter =>{filed_name => value}})
  %h5 Example: client.search('test', {:field => 'test', :type => 'test', :category_filter =>{'laptop' => ['apple']}})
  %h5 Response: {"took"=>10, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>2, "max_score"=>1.6931472, "hits"=>[{"_index"=>"test-api-key-test", "_type"=>"test", "_id"=>"1", "_score"=>1.6931472, "_source"=>{"text"=>"test", "title"=>"One", "laptop"=>["dell", "apple"]}}, {"_index"=>"test-api-key-test", "_type"=>"test", "_id"=>"2", "_score"=>1.6931472, "_source"=>{"text"=>"test", "title"=>"two", "laptop"=>["acer", "apple"]}}]}, "facets"=>{"laptop"=>{"_type"=>"terms", "missing"=>0, "total"=>4, "other"=>0, "terms"=>[{"term"=>"apple", "count"=>2}, {"term"=>"dell", "count"=>1}, {"term"=>"acer", "count"=>1}]}}}
%h3 Delete index by id
.well
  %h5 client.delete('_type:id')
  %h5 Example: client.delete('test:1')
%h2 Sorting
%h3 Field
.well
  %h5 document_1 = {:text => 'test', :title => 'One', :price => '100'}
  %h5 document_2 = {:text => 'test', :title => 'two', :price => '200'}
  %h5 Example: client.add('test:1', document_1)
  %h5 Example: client.add('test:2', document_2)
  %h5 client.search(query_term, {:field => field_name, "sort" => {:fields => {:field_name => order}}})
  %h5 Example: client.search('test', {:field => 'text', "sort" => {:fields => {:price => 'asc'}}})
  %h5 Response: {"took"=>2, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>2, "max_score"=>nil, "hits"=>[{"_index"=>"test-api-key-index", "_type"=>"test", "_id"=>"2", "_score"=>nil, "_source"=>{"text"=>"test", "title"=>"two", "price"=>"200"}, "sort"=>["200"]}, {"_index"=>"test-api-key-index", "_type"=>"test", "_id"=>"1", "_score"=>nil, "_source"=>{"text"=>"test", "title"=>"One", "price"=>"100"}, "sort"=>["100"]}]}} 

%h3 GeoLocation
%h5 Add GeoLocation Function
.well
  %h5 function = Khoj.function(index_name)
.well
  %h5 document_1 = {:text => 'test', :location => {:lat => '100.00', :lon => "100.00"}}
  %h5 document_2 = {:text => 'test', :location => {:lat => '200.00', :lon => "200.00"}}
  %h5 Example: client.add('test:1', document_1)
  %h5 Example: client.add('test:2', document_2)
  %h5 client.search(query_term, {:field => field_name, "sort" => {:geo_location => {:cordinates => ["xx,yy"]}}})
  %h5 Example: client.search('test', {:field => 'title', "sort" => {:geo_location => {:cordinates => ["100,100"]}}})
  %h5 Response:{"took"=>4, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0}, "hits"=>{"total"=>2, "max_score"=>nil, "hits"=>[{"_index"=>"test-api-key-index", "_type"=>"test", "_id"=>"1", "_score"=>nil, "_source"=>{"text"=>"test", "location"=>{"lat"=>"100.00", "lon"=>"100.00"}}, "sort"=>[1.7976931348623157e+308]}, {"_index"=>"test-api-key-index", "_type"=>"test", "_id"=>"2", "_score"=>nil, "_source"=>{"text"=>"test", "location"=>{"lat"=>"200.00", "lon"=>"200.00"}}, "sort"=>[1.7976931348623157e+308]}]}}  

app/views/indices/_index.html.haml
%tr
  %td= index_counter + 1
  %td= index.name || '----'
  %td= index.document_count || '----'
  %td= index.created_at.strftime("%d/%m/%Y")

app/views/indices/index.html.haml
.page-header
  %h1
    Indices
    %small all index and document count
.row
  .span10
    - if @indices.any?
      %table.bordered-table
        %tr
          %th Sr no
          %th Name
          %th Document Count
          %th Created At
          %tr
            = render :partial => 'index', :collection => @indices
    - else
      %h3 No Indices registered !!!

  

app/views/layouts/_alerts.html.haml
- if flash.present?
  - content_for :alerts do
    .container
      .alert-message.block-message.fade.in{:class => flash.keys.first, 'data-alert' => :alert}
        %a.close{:href => "#"} ×
        %p
          %strong= flash[flash.keys.first]

app/views/layouts/application.html.haml
- unless content_for? :alerts
  = render 'layouts/alerts'

- unless content_for? :layout_content
  - content_for :layout_content do
    = yield(:alerts)
    .container
      .content
        = yield
  
- unless content_for? :layout_header
  - content_for :layout_header do
    %h2
      Welcome to Khoj, searching is now far more better and simple.
    .topbar-wrapper{:style => "z-index: 5;"}
      .topbar{"data-dropdown" => "dropdown"}
        .topbar-inner
          .container
            = render 'layouts/shared/header'

= render :file => 'layouts/base'

app/views/layouts/base.html.haml
!!!
%html
  %head
    = stylesheet_link_tag    "application"
    = stylesheet_link_tag    "bootstrap.css"
    = javascript_include_tag "application"
    = csrf_meta_tags
  
  %body
    = yield(:layout_header)
    = yield(:layout_content) or yield

app/views/layouts/shared/_header.html.haml
:javascript
  $('#dropdown').dropdown();
  $(".alert-message").alert();
%h3
  %a{:href => "#"} Khoj Registration
%ul.nav
  - if user_signed_in?
    %li
      = link_to "Personal Info",root_path 
    %li
      = link_to "View indices", user_indices_path(current_user)
  - else
    %li.active
      = link_to "Home", root_path
  %li
    = link_to "Info", info_path 
  %li.dropdown
    %a.dropdown-toggle{:href => "#"} Account
    %ul.dropdown-menu
      - if user_signed_in?
        %li
          = link_to "Sign Out", destroy_user_session_path, :title => "Log Out", :method => :delete
      - else
        %li
          = link_to "Sign In", new_user_session_path
        %li.divider
        %li
          = link_to "Sign Up", new_user_registration_path
- unless user_signed_in?
  = form_for "user", :url => user_session_path, :as => :post, :html => {:class => 'pull-right'} do
    = text_field "user", "email", :placeholder => "E-Mail", :class => "input-small"
    = password_field "user", "password", :placeholder => "Password", :class => "input-small"
    %button.btn{:type => "submit"} Sign in